title:              DalYeoU's Devlog
# email:              your-email@example.com
description:        To the game developer
author:             DalYeoU
baseurl:            "" # the subpath of your site, e.g. /blog
url:                "https://DalYeoU.github.io"

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll


# Social Profiles
twitter_username:   
github_username:    # DalYeoU
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   # UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
